/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        System.out.println("Hello World!");
        System.out.println("Hello World 2!");
        System.out.println("Hello World 3!");
        System.out.println("Hello World 4!");
        return true;
    }
}
